version: "3"

services:
    postgres:
        image: postgres:14
        container_name: easyappointments-database
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=easyappointments
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini

volumes:
    pgdata: {}
